# Generated by Django 4.2.1 on 2023-06-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='is_active',
        ),
    ]
