# Generated by Django 4.2.1 on 2023-06-01 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auction_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='start_time',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
