# Generated by Django 4.2.1 on 2023-06-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_end_time_auction_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
