# Generated by Django 4.2.1 on 2023-06-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
