# Generated by Django 4.2.1 on 2023-06-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_comment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
